file_format: "1"
id: sofle
name: Sofle
url: https://github.com/tokyo2006/zmk-config-sofle
type: board
arch: arm
features:
  - keys
  - display
outputs:
  - usb
  - ble
siblings:
  - sofle_left
  - sofle_right